<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Opengento\DocumentWidget\ViewModel\Document\Toolbar\ViewMode;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var ViewMode $viewMode */
$viewMode = $block->getData('viewMode');
?>
<?php if ($viewMode->isEnabled()): ?>
    <div class="modes">
        <strong class="modes-label" id="modes-label"><?= $escaper->escapeHtml(__('View as')) ?></strong>
        <?php foreach ($viewMode->getModes() as $code => $label): ?>
            <?php if ($viewMode->isActive($code)): ?>
                <strong title="<?= $escaper->escapeHtmlAttr($label) ?>"
                        class="modes-mode active mode-<?= $escaper->escapeHtmlAttr($code) ?>"
                        data-value="<?= $escaper->escapeHtmlAttr($code) ?>">
                    <span><?= $escaper->escapeHtml($label) ?></span>
                </strong>
            <?php else: ?>
                <a class="modes-mode mode-<?= $escaper->escapeHtmlAttr($code) ?>"
                   title="<?= $escaper->escapeHtmlAttr($label) ?>"
                   href="<?= $escaper->escapeUrl($block->getUrl('*/*/*', ['_current' => true, '_query' => [ViewMode::PARAM_NAME => $code]])) ?>"
                   data-role="mode-switcher"
                   data-value="<?= $escaper->escapeHtmlAttr($code) ?>"
                   id="mode-<?= $escaper->escapeHtmlAttr($code) ?>"
                   aria-labelledby="modes-label mode-<?= $escaper->escapeHtmlAttr($code) ?>">
                    <span><?= $escaper->escapeHtml($label) ?></span>
                </a>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
