<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Html\Link;

/** @var Link $block */
/** @var Escaper $escaper */
?>
<div class="widget block block-document-link">
    <a <?= $block->getLinkAttributes() ?>><span><?= $escaper->escapeHtml($block->getLabel()) ?></span></a>
</div>
