<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Html\Link;
use Opengento\Document\Api\Data\DocumentInterface;
use Opengento\DocumentWidget\ViewModel\Document\Image;

/** @var Link $block */
/** @var Escaper $escaper */

/** @var Image $imageHelper */
$imageHelper = $block->getData('imageHelper');
/** @var DocumentInterface $document */
$document = $block->getData('document');
?>
<div class="widget block block-document-link">
    <a <?= $block->getLinkAttributes() ?>>
        <span><?= $block->getChildBlock('imageRenderer')->setData('image', $imageHelper->getImage($document, 'document_widget_link'))->toHtml() ?></span>
    </a>
</div>
