<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Opengento\Document\Model\ResourceModel\Document\Collection;
use Opengento\DocumentWidget\ViewModel\Document\Toolbar;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var Toolbar $toolbar */
$toolbar = $block->getData('toolbar');
/** @var Collection $collection */
$collection = $block->getData('collection');
?>
<?php if ($collection->getSize()): ?>
    <div class="toolbar toolbar-documents">
        <?php if ($toolbar->isExpanded()): ?>
            <?= $block->getChildHtml('viewMode') ?>
        <?php endif; ?>
        <?= $block->getChildBlock('pager')->setCollection($collection)->toHtml() ?>
        <?php if ($toolbar->isExpanded()): ?>
            <?= $block->getChildHtml('sorter') ?>
        <?php endif; ?>
    </div>
<?php endif ?>
